server:
  port: 8080 # Le port d'entrée de ton système

spring:
  cloud:
    config:
      enabled: false # Désactive le client Config pour éviter les erreurs si aucun serveur Config n'est disponible
    gateway:
      routes:
        - id: service-utilisateur-route
          uri: lb://SERVICE-UTILISATEUR # "lb://" utilise LoadBalancer avec Eureka
          predicates:
            - Path=/api/users/** # Toute requête commençant par /api/users/
          filters:
            - StripPrefix=1            # Enlève "/api" avant d'envoyer au service

        - id: google-search-test
          uri: https://www.google.com
          predicates:
            - Path=/google/**