name: transcendence

services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  api42-postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${API42_POSTGRES_DB}
      POSTGRES_USER: ${API42_POSTGRES_USER}
      POSTGRES_PASSWORD: ${API42_POSTGRES_PASSWORD}
    volumes:
      - api42-pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${API42_POSTGRES_USER} -d ${API42_POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  regular-user-postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${REGULAR_USER_POSTGRES_DB}
      POSTGRES_USER: ${REGULAR_USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${REGULAR_USER_POSTGRES_PASSWORD}
    volumes:
      - regular-user-pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${REGULAR_USER_POSTGRES_USER} -d ${REGULAR_USER_POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: containers/Dockerfile
    depends_on:
      - api-gateway
    restart: unless-stopped

  auth-service:
    build:
      context: ../backend/auth-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      FORTYTWO_CLIENT_ID: ${FORTYTWO_CLIENT_ID}
      FORTYTWO_CLIENT_SECRET: ${FORTYTWO_CLIENT_SECRET}
      FORTYTWO_REDIRECT_URI: ${FORTYTWO_REDIRECT_URI}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  group-service:
    build:
      context: ../backend/group-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  chat-service:
    build:
      context: ../backend/chat-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  api42-service:
    build:
      context: ../backend/api42-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_HOST: api42-postgresql
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${API42_POSTGRES_DB}
      POSTGRES_USER: ${API42_POSTGRES_USER}
      POSTGRES_PASSWORD: ${API42_POSTGRES_PASSWORD}
      API42_UID: ${API42_UID}
      API42_SECRET: ${API42_SECRET}
      API42_NEXT_SECRET: ${API42_NEXT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - api42-images:/app/uploads
    depends_on:
      api42-postgresql:
        condition: service_healthy
    restart: unless-stopped

  regular-user-service:
    build:
      context: ../backend/regular-user-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_HOST: regular-user-postgresql
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${REGULAR_USER_POSTGRES_DB}
      POSTGRES_USER: ${REGULAR_USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${REGULAR_USER_POSTGRES_PASSWORD}
      REGULAR_USER_JWT_KEY: ${REGULAR_USER_JWT_KEY}
      REGULAR_USER_EMAIL: ${REGULAR_USER_EMAIL}
      REGULAR_USER_APP_PASSWORD: ${REGULAR_USER_APP_PASSWORD}
    volumes:
      - regular-user-images:/app/uploads
    depends_on:
      regular-user-postgresql:
        condition: service_healthy
    restart: unless-stopped

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    # ports:
    #   - "8088:8088"
    depends_on:
      - auth-service
      - group-service
      - chat-service
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
      - frontend
      - grafana
      

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SERVER_DOMAIN: grafana.suite42.dev
      GF_SERVER_ROOT_URL: https://grafana.suite42.dev
      GF_SERVER_HTTP_PORT: 8086
    ports:
      - "8086:8086"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  pg_data:
  api42-pg:
  api42-images:
  regular-user-pg:
  regular-user-images:
  prometheus-data:
  grafana-data:
