server:
  port: 8080
  servlet:
    context-path: /api/group

spring:
  application:
    name: group-service

app:
  jwt:
    secret: ${JWT_SECRET}
    cookie-name: access_token

management:
  endpoints:
    web:
      exposure:
        include: health,info
