server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service

  security:
    oauth2:
      client:
        registration:
          42:
            client-id: ${FORTYTWO_CLIENT_ID}
            client-secret: ${FORTYTWO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${FORTYTWO_REDIRECT_URI}
            scope: public
        provider:
          42:
            authorization-uri: https://api.intra.42.fr/oauth/authorize
            token-uri: https://api.intra.42.fr/oauth/token
            user-info-uri: https://api.intra.42.fr/v2/me
            user-name-attribute: login

management:
  endpoints:
    web:
      exposure:
        include: health,info
