# H2 database for dev -Dspring.profiles.active=dev
spring.datasource.url=${H2_URL}
spring.datasource.username=${H2_USER}
spring.datasource.password=${H2_PASS}
spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.mode=never
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update