# Common properties
spring.application.name=42-api-service
server.port=8084
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

api42.upload-location=/app/uploads
api42.image-domain=https://localhost/images42/
api42.default-banner=default_profile_banner.jpg
api42.default-avatar=default_profile_avatar.jpg

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

api42.secret=${API42_SECRET}
api42.uid=${API42_UID}
api42.next-secret=${API42_NEXT_SECRET}
