/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSections: typeof import('./components/sections/IndexSections/AboutSections.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BigRedButton: typeof import('./components/ui/BigRedButton.vue')['default']
    ConnectConnector: typeof import('./components/ui/ConnectConnector.vue')['default']
    Corner: typeof import('./components/ui/Corner.vue')['default']
    DoubleConnectors: typeof import('./components/ui/DoubleConnectors.vue')['default']
    EndConnector: typeof import('./components/ui/EndConnector.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSections: typeof import('./components/sections/LoginSections/HeroSections.vue')['default']
    IndexSections: typeof import('./components/sections/IndexSections/IndexSections.vue')['default']
    LabeledCorner: typeof import('./components/ui/LabeledCorner.vue')['default']
    LoginSections: typeof import('./components/sections/LoginSections/LoginSections.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupSections: typeof import('./components/sections/SignupSections/signupSections.vue')['default']
    SingleConnectionConnector: typeof import('./components/ui/SingleConnectionConnector.vue')['default']
    SingleConnector: typeof import('./components/ui/SingleConnector.vue')['default']
    SingleEndConnectors: typeof import('./components/ui/SingleEndConnectors.vue')['default']
    TechSections: typeof import('./components/sections/IndexSections/TechSections.vue')['default']
    ToolCard: typeof import('./components/ui/ToolCard.vue')['default']
    ToolkitSections: typeof import('./components/sections/IndexSections/ToolkitSections.vue')['default']
    TripleConnectors: typeof import('./components/ui/TripleConnectors.vue')['default']
  }
}
