server:
  port: 8082
  servlet:
    context-path: /api/chat

spring:
  application:
    name: chat-service

app:
  jwt:
    secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
