# H2 database for dev -Dspring.profiles.active=dev
spring.datasource.url=jdbc:h2:./data/users.db
spring.datasource.username=${REGULAR_USER_H2_USER}
spring.datasource.password=${REGULAR_USER_H2_PASS}
spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.mode=never
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
