# Common properties
spring.application.name=regular-user-service
server.port=8085
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
spring.jpa.defer-datasource-initialization=false
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

regUser.upload-location=/app/uploads
regUser.image-domain=http://localhost:8085/images-regular/
regUser.default-banner=default_profile_banner.jpg
regUser.default-avatar=default_profile_avatar.jpg

spring.mail.host=smtp.gmail.com
spring.mail.username=${REGULAR_USER_EMAIL}
spring.mail.password=${REGULAR_USER_APP_PASSWORD}
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG
